[INSPO-86] inbox service와 API GATEWAY 연동
YAPP-Github/24th-Web-Team-2-BE pull request #31
Opened 2024-08-06 11:49 UTC by EeeasyCode

## Issue Number
INSPO-86

## 작업 내용
inbox service에서 api-gateway에 노출되어야 할 service들을 연동하는 작업을 진행했습니다.
- Get /subscriptions <-> inboxService getSubscriptions 
- Post /subscriptions <-> inboxService addSubscription
- Get /spams <-> inboxService getSpams
- Post /spams <-> inboxService addSpam
- Post /interests <-> inboxService addInterest

Session 저장소에서 userId를 가져오는 중복 코드를 제거하기 위해, @AuthInfo 데코레이터를 구현했습니다.
해당 데코레이터는 Controller의 파라미터 데코레이터로 사용되며, 세션의 auth 정보를 가져와 반환합니다.

Session 의 검증을 위한 Auth Guard를 구현했습니다.
아직 컨트롤러에 적용하지 않았고, 내부 구현도 디테일하지 않아 우선 가벼운 구현만 진행했습니다.

더 이상 사용되지 않는 Passport 라이브러리 코드를 제거했습니다.

## Reference

## Check List

2024-08-07 15:58 UTC, leobang17 requested changes
코멘트 확인해주세요! 
고생했습니다 ^__^

2024-08-07 15:58 UTC, leobang17 commented on apps/api-gateway/src/common/guards/auth.guard.ts
> +  }
타이핑을 위해서라면 type assertion을 활용할 수 있어요.
물론 `session` 객체가 항상 해당 type이라는 것을 개발자 측에서 보장해야하지만,, 

저는 예전 코드 보니까 type assertion으로 커스텀 세션 타입을 지정했었네요.


``` typescript
const session = request.session as CustomSession;

return session && session.user ;
```

요런 식이 될 듯?

예전에 나는 `ExecutionContext`랑 `ArgumentHost`를 다루는 객체를 따로 만들었었음. 
거기서 session도 관리하고.

2024-08-07 15:58 UTC, leobang17 commented on apps/api-gateway/src/common/decorators/auth-info.decorator.ts
> +// 데코레이터, AOP 정리
`request` 객체는 일단은 nestjs 측에서 제공하는건 없지 않나요??

nest 플랫폼에 대한 의문인가···?

2024-08-07 15:58 UTC, leobang17 commented on apps/api-gateway/src/api/inbox/inbox.module.ts
> +          port: parseInt(process.env.INBOX_PORT_DEV),
어 이 환경변수는 container 내부에서 1번 프로세스 (여기서는 nestjs 앱) 가 점유하는 포트입니다.
지금은 다 3000번으로 고정입니다.

통신을 위해서는 머신에서 해당 container가 inbound하는 포트를 지정해줘야 해요. 
아직 환경변수로 등록이 안되어있을텐데, 일단 지금 inbox는 3002번이네요.

이 부분은 수정해야할듯!!

2024-08-07 15:58 UTC, leobang17 commented on apps/api-gateway/src/api/inbox/inbox.controller.ts
> +}
급하지 않다면 이 친구는 다른 곳에 배치하는게 어떨지 ??

2024-08-08 06:35 UTC, EeeasyCode commented on apps/api-gateway/src/common/guards/auth.guard.ts
> +  }
음 우선 타입 단언은 최대한 지양하고 싶어서 고민했던 부분이라

```typescript
export interface IRequest extends Request {
  session: {
    auth: AuthType;
  };
}

type AuthType = {
  authId: number;
  userId: string;
  role: string;
  providerType: string;
  accessToken: string;
};

```
로 세션 타입을 지정하려고 합니다. 추가 의견 부탁드려요!

실행 컨텍스트는 아직 따로 관리할 필요가 없을 것 같아서 지정하진 않았는데, 나중에 추가해도 괜찮을 것 같아요.

2024-08-08 06:35 UTC, EeeasyCode commented on apps/api-gateway/src/common/decorators/auth-info.decorator.ts
> +// 데코레이터, AOP 정리
이건 그냥 단순한 플랫폼 적인 고민이었는데, 제가 주석을 지우지 않은 것 같네요.
제거 후 반영하도록 하겠습니다.

2024-08-08 06:35 UTC, EeeasyCode commented on apps/api-gateway/src/api/inbox/inbox.module.ts
> +          port: parseInt(process.env.INBOX_PORT_DEV),
음, 일단 환경 변수에 대한 관리를 더 해야할 것 같아요.
내부 서버에서 사용할 port는 어차피 3000번 고정이라 괜찮은데,
api-gateway에서 연결하기 위한 port는 지정해야 할테니..

그리고, 로컬 환경에서는 각 서버의 내부 포트를 3000번으로 할당해줄 수 없으니, 로컬에서 관리하는 .env 환경 변수에 대한 정의도 통합해서 관리해야할듯요!

이 부분도 함께 추가 작업 사항에 반영하도록 하겠습니다!!

2024-08-08 06:35 UTC, EeeasyCode commented on apps/api-gateway/src/api/inbox/inbox.controller.ts
> +}
이 부분은 type 으로 따로 관리하도록 하겠습니다~~ 테스트해본다고 상단에 놨다가 깜빡한 것 같아요 ㅎㅎ

2024-08-09 11:51 UTC, EeeasyCode commented
@leobang17 해당 기능 피드백 반영 완료했습니다~ 확인 후 approved 부탁드려요!

2024-08-09 14:59 UTC, leobang17 approved these changes
lgtm 입니다 ~
고생했서요

2024-08-10 11:40 UTC, merged