[HDWG-6] 소셜로그인 후 guest 유저 생성 플로우 구현
YAPP-Github/24th-Web-Team-2-BE pull request #7
Opened 2024-07-21 07:09 UTC by EeeasyCode

## Issue Number
6

## 작업 내용
- TypeORM 설정 : [#1a0c74b](https://github.com/YAPP-Github/24th-Web-Team-2-BE/commit/08dad0311bf7e844d15474bb1780927a254613cb)
- Google 로그인 후 session 발급 구현 : [#83b043c](https://github.com/YAPP-Github/24th-Web-Team-2-BE/commit/83b043c5817caf9ac95fd7a813c12cedbf6e7740)

## Reference
X

## Check List
- [ ] Google Oauth 관련 로직은 전부 api-gateway의 auth로 책임 위임했습니다.
- [ ] 현재 세션 저장소는 서버 자체의 인메모리를 사용하고 있고, redis 테스트 연동 결과는 문제 없이 잘 동작하는 것을 확인했습니다.
- [ ] 이미 동일 계정으로 가입된 계정의 경우, 바로 return 처리됩니다.
- [ ] 최초 가입 계정인 경우, guest user 생성 후 -> auth table에 provider 관련 정보, userId를 저장합니다. 
- [ ] 다음 스프린트부터 천천히 테스트 코드를 작성할 예정입니다. 기본적인 테스트 코드 환경을 구성했습니다. ->[8a41f26](https://github.com/YAPP-Github/24th-Web-Team-2-BE/commit/8a41f26327cad45d4a1604fcd080b332be0b44ea)

## Next Task
- 타입 명시를 제대로 하지 않아 해당 부분 개선 작업 진행 
- DTO 구현 및 로직 내 반영
- Redirect 논의 후 작업 진행
- 공통 라이브러리 관리 (ENUM, CONSTANT, Filter, Interceptor 등)
- 중복 로직 제거 (함수화, 추상화 진행)
- 하드 코딩되어 있는 내용 환경 변수 설정 후 공유

2024-07-22 06:52 UTC, EeeasyCode commented
[변동 사항]
- 기존 passport로 관리하던 google oauth flow를 자체 api 호출 방식으로 변경 예정
- FE 에서 인가 코드를 받으면 token 발급 및 profile 정보 호출

2024-07-23 07:58 UTC, leobang17 requested changes
고생하셨습니다~ 👍

몇 개 코멘트 달았는데 답변 부탁해용

2024-07-23 07:58 UTC, leobang17 commented on apps/api-gateway/src/main.ts
> +      secret: 'secret',
secret 같은 값은 하드코딩보다는 환경변수로 관리하면 좋을 것 같습니다.

2024-07-23 07:58 UTC, leobang17 commented on apps/auth/src/auth.module.ts
> +          port: 3002,
연결 정보도 환경변수로 일괄적으로 관리하는게 좋을 것 같아요. 
특히 port는 서비스가 많아서!!

2024-07-23 07:58 UTC, leobang17 commented on apps/auth/src/main.module.ts
> +      type: 'mysql',
DB 커넥션 정보도 환경변수로 고고

2024-07-23 07:58 UTC, leobang17 commented on apps/auth/src/main.module.ts
> +      envFilePath: ['.env', 'apps/auth/.env'],
`.env` 파일은 배포환경에 어떻게 전달할 예정인가요?

2024-07-23 07:58 UTC, leobang17 commented on apps/auth/src/main.ts
> +    },
얘도 환경변수로 관리 고고 
그리고 각 마이크로서비스 프로세스가 노출하는 포트는 동일합니다. (일단 dockerfile 스크립트 정의된 바로는 3000번으로)

2024-07-23 07:58 UTC, leobang17 commented on apps/user/src/main.module.ts
> +      database: 'hdwg_dev_user',
위와 同

2024-07-23 07:58 UTC, leobang17 commented on apps/user/src/main.ts
> +    },
위와 同

2024-07-23 07:58 UTC, leobang17 commented on apps/auth/src/entity/auth.entity.ts
> +@Index(['providerType', 'providerId'], { unique: true })
이거 복합인덱스 정의하는 인덱스 맞죠?!
providerType > providerId 순으로 복합 인덱스를 정의한 이유가 있을까요? 
조회하는 대부분의 케이스는 userId를 기반으로 색인할 것 같아서 제 생각에는 필요 없을 것 같은데 다른 의도가 있다면 설명해주세요~~!!

--- 
그리고 제가 엔티티 정의하는 이전 pr을 리뷰 못하고 머지된 것 같은데, db정의했던 거랑 조금 내용이 다른 것 같아요.

user와 auths는 1대1,
auths와 oauth2_providers가 1대 다 관계였던 거로 기억해요. 
답변 부탁드립니다.

2024-07-26 10:12 UTC, EeeasyCode commented on apps/auth/src/auth.module.ts
> +          port: 3002,
해당 내용 포함한 환경변수 관리는 다음 PR에 적용하여 피드백 반영할게요!

2024-07-26 10:13 UTC, EeeasyCode commented on apps/auth/src/main.module.ts
> +      envFilePath: ['.env', 'apps/auth/.env'],
디스코드에서 이야기 나눈대로 docker image 빌드 과정에서 같이 말아서 올리는거죠??!

2024-07-26 10:25 UTC, EeeasyCode commented on apps/auth/src/entity/auth.entity.ts
> +@Index(['providerType', 'providerId'], { unique: true })
우선 복합인덱스 정의에 대해서 먼저 답변드릴게요!
providerType과 providerId를 묶어서 중복을 방지하기 위한 목적으로 사용했습니다.
조회는 userId 기반으로 인덱스 걸어놓고 사용하면 될 것 같아요.

2024-07-26 10:27 UTC, EeeasyCode commented on apps/auth/src/entity/auth.entity.ts
> +@Index(['providerType', 'providerId'], { unique: true })
그리고, 엔티티는 아직 정규화를 진행하지 않고 최대한 테이블 수를 늘리지 않으려 auth와 user만 분리해둔 상태이고, 아마 다음 PR 때 정리해서 auth 테이블 정규화 진행하면 말씀하신 auth와 provider 를 1:N으로 분리할 것 같아용!

2024-07-26 10:29 UTC, EeeasyCode commented
우선, passport google 제거 후, 직접 accessToken과 profile을 받아오도록 수정했습니다.
추가 기능인 accessToken 재발급 로직과 피드백 반영해서 다음 PR로 올릴게요~!

2024-07-26 16:16 UTC, leobang17 commented on apps/auth/src/main.module.ts
> +      envFilePath: ['.env', 'apps/auth/.env'],
음 빌드할 때 넣는게 아니라 
이미지 > 컨테이너로 띄울 때 전달하려고 했어요. (docker-compose 통해서)

2024-07-26 16:19 UTC, leobang17 commented on apps/auth/src/entity/auth.entity.ts
> +@Index(['providerType', 'providerId'], { unique: true })
넵넵 굳입니다

2024-07-26 16:22 UTC, leobang17 commented on apps/auth/src/auth.service.ts
>          userId: 'asdfasd222',
이건 예전 커밋분이긴한데 아직 db연동이 안돼서 일단은 string값을 임의로 넣은거죠?

2024-07-27 08:05 UTC, EeeasyCode commented on apps/auth/src/auth.service.ts
>          userId: 'asdfasd222',
아 user 쪽 프로세스 변경될 것 같아서 일단 임의값 넣은거에요!! 
다음 PR에 연동될 예정!

2024-07-27 08:06 UTC, EeeasyCode reviewed
@leobang17 
확인 후, Approve 요청드립니다!

2024-07-27 08:22 UTC, merged